### ISSUE TITLE
Error using latest jquery-3.6.0

### ISSUE THREAD

**Issue by emanuelriolan** [gyrocode/jquery-datatables-checkboxes#131]
![image](https://user-images.githubusercontent.com/47812270/130637971-5747c3d3-78ed-41e6-9496-4bfa5907d646.png)

**Comment by mpryvkin** [comment]
I have tested with jquery 3.6.0 but could not replicate the issue. Can you please create anexample on jsFiddle.net demonstrating the problem using [this example](https://jsfiddle.net/gyrocode/snqw56dw/) as a start? Thanks!

**Comment by emanuelriolan** [comment]
This  example on jsFiddle sir. https://jsfiddle.net/emanuelriolan/d3mc8vtb/9/

**Comment by mpryvkin** [comment]
Thanks for the example. The problem is not in jQuery version. It is not documented well but the solution to this problem is to use `dt-checkboxes` class for input element, please see [this example](https://jsfiddle.net/bk80uc2s/). As for now this class is required on `input` element when rendering custom checkbox.
