### ISSUE TITLE
Save/restore checkboxes selection when state saving is enabled

### ISSUE THREAD

**Issue by gkreddy** [gyrocode/jquery-datatables-checkboxes#14]
Currently in datatable we have "bStateSave" ( save datatable state(pagination, sort, etc) in cookie). is there any provision/setting for checkbox plugin to save its state?

**Comment by Fonata** [comment]
Is there any way we can have bStateSave on and make DataTables not remember selected rows on a full page reload? 

I am asking because in our application, the row selection is retrieved in the database. If the user selects something without hitting our apps 'Save selection' button, navigates away and comes back, they expect the pristine state from the database, but instead get their previous selection.
