### ISSUE TITLE
Select/deselect checkboxes from all pages in server-side processing mode

### ISSUE THREAD

**Issue by s0By** [gyrocode/jquery-datatables-checkboxes#19]
Select all is turned off in my solution and I'm using serverside. 

Is there a way to deselect everything on all pages (clear)? 
The deselect function clears only on the current page.

**Comment by mpryvkin** [comment]
There have been an attempt to implement support for selecting/deselecting records from all pages in server-side processing mode by [rinkside](https://github.com/rinkside/jquery-datatables-checkboxes). See [this thread](http://www.gyrocode.com/articles/jquery-datatables-row-selection-using-checkboxes-and-select-extension/comment-page-1/#comment-6281) or [this commit](https://github.com/rinkside/jquery-datatables-checkboxes/commit/2c5b61cf03422690a9728757299df4e0551bd06a). 

However checked "select all" checkbox would require special handling by the server-side script, because only current page data is available for the plug-in.

**Comment by hycday** [comment]
would this commit add the "deselect" ability to all pages and not only current one, with server-side processing mode ?

**Comment by mpryvkin** [comment]
Yes, it should.

**Comment by hycday** [comment]
I see that the changes suggested in this commit are done on a base that is different from the current dataTables.checkboxes.js file. Not sure how to get the correct last version of dataTables.checkboxes.js with this commit's changes ?

**Comment by mpryvkin** [comment]
Oh, didn't realize you were talking about the [commit by rinkside](https://github.com/rinkside/jquery-datatables-checkboxes/commit/2c5b61cf03422690a9728757299df4e0551bd06a). It's been awhile since I checked. I was talking more about the future update.

**Comment by s0By** [comment]
How's it going with future updates anyway? Did you Check my other issues that I mentioned before?

**Comment by mpryvkin** [comment]
I am working on 1.2 release (see master branch) that improves performance, fixes bugs and adds some other features (like support of plugins like iCheck, etc.)

I am still unsure whether there is a need for server-side all pages selection due to complexity of the server-side implementation that would be needed. For example, you would need to handle three variables instead of one: state of "select all" control, list of checked cells, list of unchecked cells. And use some logic to figure out what user selected based on state of these variables.

**Comment by s0By** [comment]
I agree with your doubt about making an all-page selection. It will probably confuse people and bring a lot of mistake human factors. But you definitely need to be able to deselect all pages at once.

**Comment by mpryvkin** [comment]
I totally agree with you, you make a very good point here. I'm pushing another update today and I will work on that next.

**Comment by hycday** [comment]
agree, I think the "deselect on all pages" is important as it's like a fix, whereass the "select all elements" is more a feature.

let me know if I can help for the "deselect on all pages" fix as I need to implement it quickly as well.

thanks !!

**Comment by mpryvkin** [comment]
I hope to implement a fix for this in the next few days.

**Comment by mpryvkin** [comment]
Gentlemen, I just pushed an update adding `checkboxes.deselectAll()` API method that will effectively deselect all checkboxes in server-side processing mode. Please test the latest version and let me know if it works for you case. Thanks!

**Comment by hycday** [comment]
oh wow. tested briefly, and works like a charm !

just noticed that the select rows count with server-side + pagination is also fixed (it was only counting current page).

you sir are great.

thanks !

**Comment by s0By** [comment]
I approve, works like a charm.
