### ISSUE TITLE
DataTables select extension compatibility?

### ISSUE THREAD

**Issue by ryanmortier** [gyrocode/jquery-datatables-checkboxes#29]
Are we supposed to use with the `select` extension or as a standalone extension?

Thank you.

**Comment by mpryvkin** [comment]
Current version 1.1.x doesn't require Select extension. Future versions most likely will require Select extension only if you need row selection functionality `selectRow: true`.

**Comment by galvarez421** [comment]
I encountered an issue with this recently due to the optional nature of using the Select extension and the way that the UMD wrapper is written. Because https://github.com/gyrocode/jquery-datatables-checkboxes/blob/1.2.11/js/dataTables.checkboxes.js#L21 does not require the Select extension, implementing the module requires setting up your own dependency mapping/setup. For example, the following code (example code for RequireJS setup) can result in a race condition since the plugin code will not know to wait for the Select extension to load:

```
require(["jquery", "datatables", "datatablesSelect", "datatablesCheckboxes"], function($) {
  // Code depending on Checkboxes plugin -- may or may not work due to dependency race condition
});
```

There are of ways to get around this but it's not ideal, for example:

```
require(["jquery", "datatables", "datatablesSelect"], function($) {
  require(["datatablesCheckboxes"], function() {
    // Code depending on Checkboxes plugin -- should work because of nested requires
  });
});
```

One idea to address this would be to distribute two separate files, e.g., datatables.checkboxes.js and datatables.checkboxes.select.js, where the latter would include the Select extension as a dependency via the UMD wrapper and the former would not. With this divergence, you could probably also afford to make the Select-_incompatible_ file leaner by not having to include code to make it work with the Select extension.

**Comment by mpryvkin** [comment]
Thanks for your feedback. 

I definitely don't want to split code into two versions. If your workaround works, why do you consider as not ideal? It seems OK to me.

I have to test the code but [this condition](https://github.com/gyrocode/jquery-datatables-checkboxes/blob/1.2.11/js/dataTables.checkboxes.js#L197) possibly is true (unverified) even if Select extension is not yet loaded and possibly is a result of setting [select](https://datatables.net/reference/option/select) to `true`.

**Comment by galvarez421** [comment]
I think it's not ideal because one of the main benefits of using AMD is, per [the AMD wiki](https://en.wikipedia.org/wiki/Asynchronous_module_definition):

> Fewer page errors. AMD implementations allow developers to define dependencies that must load before a module is executed, so the module does not try to use outside code that is not available yet.

Granted, the integration with the Select extension is optional, which is why I suggested creating different distributions. I'm not sure what other patterns might exist for a scenario like this, in which there are optional dependencies.
