### ISSUE TITLE
Select all checkbox and selected rows count wrong in Edge

### ISSUE THREAD

**Issue by os1r1s110** [gyrocode/jquery-datatables-checkboxes#34]
Here is the problem I encountered:
1. Use a table which has more rows than what is displayed in each page so there is a need for paging
2. On Edge, select some rows by using their checkboxes individually
3. Then, the "tristate" checkbox get filled with black square, click on it. On chrome, it would deselect all rows, on Edge, it selects all. 
4. Then click the "select all" checkbox to deselect all rows again, and observer the "selected rows" count, it should be wrong. 

JS Fiddle: https://jsfiddle.net/hfxz7hna/2/

**Comment by mpryvkin** [comment]
Thanks for reporting!

**Comment by mpryvkin** [comment]
I tried to retain support for duplicate data in the column but your example shows that it may be impossible with all the plug-ins involved. I dropped support for duplicate data in order to fix the issue with Edge.

See [updated example](https://jsfiddle.net/hfxz7hna/4/) where it now should work as expected.

**Comment by mpryvkin** [comment]
Thank you for reporting this issue.

**Comment by os1r1s110** [comment]
Thanks for the quick fix!
