### ISSUE TITLE
checkboxes.selectRow = false still toggles row class 'selected'

### ISSUE THREAD

**Issue by Webkungen** [gyrocode/jquery-datatables-checkboxes#42]
Having this code:

`columnDefs: [
	{ orderable: false, targets: [ -1 ] },
	{
		targets: 0,
		className: 'dt-head-center dt-body-center',
		checkboxes: {
			selectRow: false
		},
		width: 20,
	}
],`

The row still gets the 'selected' class and gives the impression the checkbox is checked (but it's not). The row class should only toggle when selectRow is set to true?

**Comment by mpryvkin** [comment]
Setting `checkboxes: { selectRow: false }` only disables row selection when checkbox is clicked. This doesn't prevent row selection if you click on the row because it is controlled by separate [Select](https://datatables.net/extensions/select/) extension.

If you don't want to have row selection at all, you also need to remove `select` option in addition to setting `checkboxes: { selectRow: false }`, see [this example](https://jsfiddle.net/snqw56dw/761/).
