### ISSUE TITLE
CheckAll does not work when table has scrollable properties

### ISSUE THREAD

**Issue by vmosoti** [gyrocode/jquery-datatables-checkboxes#52]
If you set the table to below properties, the CheckAll checkbox does not activate the others

 ```
scrollY: 450,
scroller: true,
scrollX: true,
```
let me know any settings I am missing.

**Comment by mpryvkin** [comment]
Do you use the most recent version of the plug-in? 

I added the options you've mentioned and it seems to work just fine, see [this example](https://jsfiddle.net/snqw56dw/1154/).

**Comment by vmosoti** [comment]
Yes I have the latest version.
Looks like a problem when using iCheck. Could you give an example based on iCheck please.

**Comment by mpryvkin** [comment]
I see the problem now, good point. The problem is in the selector for the table container. You need to either add a container element for the table and use its ID or add `_wrapper` to the table ID to get container element created by jQuery DataTables.

See [this example](https://jsfiddle.net/vn42xxsn/1/) for code and demonstration.

**Comment by vmosoti** [comment]
Awesome. That worked.
