### ISSUE TITLE
issue when using  scrollY

### ISSUE THREAD

**Issue by dotnetdeveloper67** [gyrocode/jquery-datatables-checkboxes#80]
When using the `scrollY` setting I'm not able to  capture the select all click event.

This works when i do not have `scrollY`  setting set.  
```
$('#NotificationDataTable thead th input[type="checkbox').on('click',function(e) {
   alert("thead");
});
```

When it's set nothing  happens

**Comment by mpryvkin** [comment]
I would recommend using [`selectAllCallback`](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/reference/options/#columns.checkboxes.selectAllCallback) option instead of catching the click event yourself.

However if you still want to do that, see if delegated event handler works (untested):

```
$('#NotificationDataTable thead th').on('click', 'input[type="checkbox"]', function(e) {
   alert("thead");
});
```
