### ISSUE TITLE
The selected row count is stuck after updating the rows.

### ISSUE THREAD

**Issue by Lb-lea** [gyrocode/jquery-datatables-checkboxes#89]
![capture du 2018-12-20 13-46-17](https://user-images.githubusercontent.com/16864438/50288573-9b49ef80-0466-11e9-8b1c-7927eb55867d.png)
I had a table with 3 entries, I externally changed the table content so I have only two rows now. But the selected row count is still on 3.
 If I deselect the current rows with the deselect all button it will still say "1 row selected"

I tried to use the option
```
'fnInitComplete' : function($this) {
     this.DataTable().rows().deselect();
 }"
```

But it only deselect rows that actually exist so the missing row is not called (logic) so I still have "1 row selected".

The only way to clear it is to use ctrl-alt-R in the browser to clear the form. Only then, the rows will be deselected.

This behaviour doesn't exist when I use the "normal"  selection where we just click on the rows so I think it is linked with this plugin.

Is there a way/option to add to clean the check boxes  when the table is changed.

**Comment by mpryvkin** [comment]
There is a way to deselect all checkboxes using [`column().checkboxes.deselectAll()`](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/reference/api/#column().checkboxes.deselectAll()) API method.

jQuery DataTables Checkboxes plug-in is not aware of data changes because jQuery DataTables is lacking events when row is removed or data is changed.

For now your best bet would be:
1. Retrieve selected checkboxes using [`column().checkboxes.selected()`](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/reference/api/#column().checkboxes.selected()) API method
2. If you are not destroying the table, deselect all checkboxes using [`column().checkboxes.deselectAll()`](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/reference/api/#column().checkboxes.deselectAll()) API method.
3. Update table data.
4. Iterate over table data and if row was checked before, check it again using [`column().checkboxes.select()`](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/reference/api/#column().checkboxes.select()) or [`cell().checkboxes.select()`](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/reference/api/#cell().checkboxes.select()) API methods. See [this example](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/api/select-checkboxes/) for demonstration.
