### ISSUE TITLE
Remove checkbox for certain row

### ISSUE THREAD

**Issue by m33ch** [gyrocode/jquery-datatables-checkboxes#9]
Hi all,

thank you for package!

Is it possible not to add input on certain row?
I try to override `render` option on my `columnDefs` but it has no effect.

Thanks

**Comment by mpryvkin** [comment]
Thanks for interesting question. Currently it's not possible with the Checkboxes extension but there is a workaround, see [this example](https://jsfiddle.net/adkx2kzp/).

Use `rowCallback` along with `select.selector` options to remove checkbox and disable row selection, see sample code below:

      'select': {
         'style': 'multi',
         'selector': 'tr:not(.no-select)'
      },
      'rowCallback': function( row, data, index ){
         if(data[2] == 'Software Engineer'){
            $('td:eq(0)', row).html('');
            $(row).addClass('no-select');
         } else {
            $(row).removeClass('no-select');
         }
       },

**Comment by NamingException** [comment]
Select All from header does not take into account this. It will select even the no-select row.

**Comment by mpryvkin** [comment]
You're right, good point. I have added handling of "select all" control, see [this example](https://jsfiddle.net/adkx2kzp/1/).

**Comment by Emarcus25** [comment]
The above example only hides the checkbox for selected rows, but when you click 'Select All' and 'Submit', it takes into count the data for that row.  To check it:
1. Go to the example
2. To limit the number or rows search for 'Brad' and you will get two rows
3. Click on 'Select All' and the submit button.
4. Under the submit button you can see the send data. As we have only two rows: one with the checkbox and other without, we should have only a date for one of the rows. Instead of it we get a data for two rows. 
5. To check that, unselect the checkboxes and select only the one without using the 'Select All' checkbox. Click on Sumbit and you will see a data only for the selected box.

**Comment by ace540i** [comment]
when i add this code the select all check box does not work. 
                    rowCallback: function (row, data, index) {
                        if (data['REQUISITION'] == '99999') {
                            $('td:eq(0)', row).html('');
                            $(row).addClass('no-select');
                        } else {
                            $(row).removeClass('no-select');
                        }
                    },

// here is call to select all 
                $('#xtrTable-select-all').on('click', function () {
                    // Check/uncheck all checkboxes in the table
                    $('input[type="checkbox"]', rows).prop('checked', this.checked);
                });

any help we be appreciated.

**Comment by ace540i** [comment]
never mind. select all is working. 
just trying to disable checkbox instead of setting html=''
great plugin!
